# setup
# A py2app setup script for building Mac apps
#
# Author:   Benjamin Bengfort <benjamin@bengfort.com>
# Created:  Sat Aug 16 11:45:57 2014 -0400
#
# Copyright (C) 2014 Bengfort.com
# For license information, see LICENSE.txt
#
# ID: setup.py [] benjamin@bengfort.com $

"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

##########################################################################
## Imports
##########################################################################

from setuptools import setup

##########################################################################
## Configuration
##########################################################################

APP = ['bin/Allusive.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

##########################################################################
## Run the setup
##########################################################################

if __name__ == '__main__':
    setup(
        app=APP,
        data_files=DATA_FILES,
        options={'py2app': OPTIONS},
        setup_requires=['py2app'],
    )
